apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-deployment
  labels:
    app: heart1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: heart1
  template:
    metadata:
      labels:
        app: heart1
    spec:
      containers:
      - name: heartweb
        image: raavi13/new:${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
